version: '3.4'

services:
  inventariosbackend:
    image: microserviciosiudsinget
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6063:6063
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
